### PR TITLE
petsc4py documentation sprint (Faversham, England, 2023)

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Review by nocollier — APPROVED** [review]
Thank you all so much for finishing this, looks great!

**Comment by dalcinl** [comment]
There are still a few missing bits (`Options` and `Object`), but these can be done incrementally.

The main branch of this repo is updated against upstream. All our changes were squashed (manually) and rebased with conflicts resolved. This is ready to upstream to core PETSc. @dham I think it is going to be easier if either Stefano or Lisandro submit the MR to core PETSc in GitLab. Before that, I would like to update GitHub Actions to use GitHub-hosted runners, maybe we can keep it running on GitHub on every sync from upstream.

**Comment by dalcinl** [comment]
PS: You can take a look at the [artifact](https://github.com/firedrakeproject/petsc_petsc4py_sprint/suites/12093892515/artifacts/636855408) from the latest build.

**Review by connorjward — APPROVED** [review]
Awesome work guys.

**Review by stefanozampini — APPROVED** [review]

**Review by Ig-dolci — APPROVED** [review]

**Review by dham — APPROVED** [review]

**Comment by dham** [comment]
Looks great, and I'm happy for one of you to put in the MR.

I'm not convinced that leaving .github in is the right thing to do. Surely this should be properly integrated with PETSc's CI rather than having a bolt-on that doesn't even run on GitLab.

Thanks to everyone for the huge amount of work.

**Comment by dalcinl** [comment]
> I'm not convinced that leaving .github in is the right thing to do.

Maybe you are right. No problem, I'll get rid of it.

@JDBetteridge @ksagiyam @mrogowski I've been waiting for your approval. If I do not hear back from you, then I'll proceed with upstreaming this PR.

**Review by JDBetteridge — APPROVED** [review]

**Review by ksagiyam — APPROVED** [review]
Thanks, all!

**Comment by dalcinl** [comment]
GitLab merge request submitted: https://gitlab.com/petsc/petsc/-/merge_requests/6313

**Comment by dalcinl** [comment]
The new petsc4py docs are now live at: https://petsc.org/main/petsc4py/

**Comment by dham** [comment]
Huge congratulations and thanks everyone!

**Pull request closed without merging**
